name: Push rockspec

on: [push]

env:
  ROCK_NAME: "crud"

jobs:
  push-scm-rockspec:
    runs-on: [ ubuntu-latest ]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master

      - name: Push scm rockspec
        run: |
          curl --fail -X PUT -F rockspec=@$ROCK_NAME-scm-1.rockspec \
            https://${{ secrets.ROCKS_USERNAME }}:${{ secrets.ROCKS_PASSWORD }}@${{ secrets.ROCKS_SERVER }}
  push-tagged-rockspec:
    runs-on: [ ubuntu-latest ]
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@master

      # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Set env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Push release rockspec
        run: |
          cat $ROCK_NAME-scm-1.rockspec |
              sed -E \
                -e "s/branch = '.+'/tag = '${GIT_TAG}'/g" \
                -e "s/version = '.+'/version = '${GIT_TAG}-1'/g" |
              curl --fail -X PUT -F "rockspec=@-;filename=$ROCK_NAME-${GIT_TAG}-1.rockspec" \
                https://${{ secrets.ROCKS_USERNAME }}:${{ secrets.ROCKS_PASSWORD }}@rocks.tarantool.org
